version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications-api
    command: npm run start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local